# Generated by Django 4.2 on 2025-08-23 02:11

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_address_user_cnic_user_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic_photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.cnic_photo_path),
        ),
        migrations.AddField(
            model_name='user',
            name='degree_photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.degree_photo_path),
        ),
    ]
